#!/usr/bin/env python3
"""
Integration test for atomspace-rocks component
Generated by OpenCog Unified integration script
"""

import unittest
import sys
import os

# Add paths for component testing
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'components'))

class TestAtomspace-rocksIntegration(unittest.TestCase):
    """Test atomspace-rocks integration with OpenCog Unified"""
    
    def setUp(self):
        """Set up test environment"""
        # Initialize test fixtures
        self.test_data = {}
        self.temp_files = []
        
    def test_atomspace_rocks_import(self):
        """Test that atomspace-rocks can be imported"""
        try:
            # Try to import atomspace-rocks related modules
            import opencog.persist.rocks
            self.assertTrue(True, "atomspace-rocks module imported successfully")
        except ImportError:
            # If atomspace-rocks is not available, check if it's in the expected location
            rocks_path = os.path.join(os.path.dirname(__file__), '..', '..', 'components', 'core', 'atomspace-rocks')
            if os.path.exists(rocks_path):
                self.assertTrue(True, "atomspace-rocks directory exists, module may need build")
            else:
                self.skipTest("atomspace-rocks module not available")
        
    def test_atomspace_rocks_basic_functionality(self):
        """Test basic atomspace-rocks functionality"""
        try:
            # Check if rocksdb is available
            import subprocess
            result = subprocess.run(['rocksdb_ldb', '--help'], 
                                 capture_output=True, text=True, timeout=10)
            if result.returncode == 0 or 'Usage:' in result.stdout:
                self.assertTrue(True, "rocksdb tools are functional")
            else:
                self.skipTest("rocksdb tools not functional")
        except (FileNotFoundError, subprocess.TimeoutExpired):
            self.skipTest("rocksdb tools not found or timed out")
        
    def test_atomspace_rocks_dependencies(self):
        """Test atomspace-rocks dependency integration"""
        # Check for required rocksdb dependencies
        required_deps = ['rocksdb', 'zlib', 'snappy', 'lz4']
        missing_deps = []
        
        for dep in required_deps:
            try:
                result = subprocess.run(['pkg-config', '--exists', dep], 
                                     capture_output=True)
                if result.returncode != 0:
                    missing_deps.append(dep)
            except FileNotFoundError:
                # pkg-config not available, skip this test
                self.skipTest("pkg-config not available for dependency checking")
        
        if missing_deps:
            self.skipTest(f"Missing atomspace-rocks dependencies: {', '.join(missing_deps)}")
        else:
            self.assertTrue(True, "All required atomspace-rocks dependencies are available")

if __name__ == '__main__':
    unittest.main()
