#!/usr/bin/env python3
"""
Integration test for moses component
Generated by OpenCog Unified integration script
"""

import unittest
import sys
import os
import subprocess

# Add paths for component testing
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'components'))

class TestMosesIntegration(unittest.TestCase):
    """Test moses integration with OpenCog Unified"""
    
    def setUp(self):
        """Set up test environment"""
        pass
        
    def test_moses_import(self):
        """Test that moses can be imported"""
        try:
            # Try to import moses-related modules
            import moses
            self.assertTrue(True, "moses module imported successfully")
        except ImportError:
            # If moses is not available, check if it's in the expected location
            moses_path = os.path.join(os.path.dirname(__file__), '..', '..', 'moses')
            if os.path.exists(moses_path):
                self.assertTrue(True, "moses directory exists, module may need build")
            else:
                self.skipTest("moses module not available")
        
    def test_moses_basic_functionality(self):
        """Test basic moses functionality"""
        try:
            # Check if moses executable is available
            import subprocess
            result = subprocess.run(['moses', '--help'], 
                                 capture_output=True, text=True, timeout=10)
            if result.returncode == 0 or 'Usage:' in result.stdout:
                self.assertTrue(True, "moses executable is functional")
            else:
                self.skipTest("moses executable not functional")
        except (FileNotFoundError, subprocess.TimeoutExpired):
            self.skipTest("moses executable not found or timed out")
        
    def test_moses_dependencies(self):
        """Test moses dependency integration"""
        # Check for required moses dependencies
        required_deps = ['boost', 'gmp', 'mpfr']
        missing_deps = []
        
        for dep in required_deps:
            try:
                result = subprocess.run(['pkg-config', '--exists', dep], 
                                     capture_output=True)
                if result.returncode != 0:
                    missing_deps.append(dep)
            except FileNotFoundError:
                # pkg-config not available, skip this test
                self.skipTest("pkg-config not available for dependency checking")
        
        if missing_deps:
            self.skipTest(f"Missing moses dependencies: {', '.join(missing_deps)}")
        else:
            self.assertTrue(True, "All required moses dependencies are available")

if __name__ == '__main__':
    unittest.main()
